version: "3.8"
services:
  # Php Application
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - .:/var/www/html/

  # Mysql Database
  db:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
volumes:
  data: